services:
  litellm-custom:
    image: keitdeck245/kdecker-litellm:v1.81.0
    environment:
      LITELLM_DEBUG: "true"
      LITELLM_PROXY_KEY: sk-1234
      LITELLM_OTEL_INTEGRATION_ENABLE_METRICS: "true"
      LITELLM_OTEL_INTEGRATION_ENABLE_EVENTS: "true"
      OPENAI_API_KEY: sk-9999
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://host.docker.internal:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "Delta"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=kdecker-o11y-for-ai-dev,service.name=litellm-custom,service.version=1.81.0"
    ports:
      - "4007:4000"
    volumes:
      - ./proxy_config_docker.yaml:/app/proxy_server_config.yaml:ro
      - ./proxy_config_docker.yaml:/app/config.yaml:ro
    command:
      - "--config"
      - "/app/config.yaml"
